### ISSUE TITLE
Slow Progress

### ISSUE THREAD

**Issue by Holyphoenix** [psychobunny/nodebb-plugin-openfantasy#1]
I thought maybe if I complained in the form of an issue on github that this was progressing slowly that you might actually work on it a little bit.  I'm sure we'd both be happy if you did make good progress!

Of course, NodeBB development probably actually comes first. :(

**Comment by zetas** [comment]
I would love this plugin to pickup steam, i'd be happy to help work on it but a todo list or project manager would be helpful.

**Comment by psychobunny** [comment]
Haha. I updated this plugin to 0.7 a few weeks ago and I worked on more of the battle code and added some new animations as well.

Closing this as its not really an "issue", but I really would love it if anybody was interested in helping out :) 

As far as a todo list is concerned, right now I'm trying to emulate the original (ADR for phpBB) as much as I can, so if you're familiar with the code and wish to port it I'd be happy to accept any PRs
