### ISSUE TITLE
Lost translation 

### ISSUE THREAD

**Issue by thanhhungtn1** [psychobunny/nodebb-plugin-openfantasy#2]
In NodeBB v0.5 it lost the translation, everything is only show the lang key

**Comment by zetas** [comment]
Not sure if this is still an issue but you can copy the translation from the install directory to the public/languages/lang/ directory manually. That's what I did and it's working fine now.

**Comment by psychobunny** [comment]
I think the translations only work on the latest master, so it should be okay when we release 0.7.0

Let me know if your NodeBB is on master or on 0.6.1 thanks :)

**Comment by zetas** [comment]
I'm on 0.7.0-dev. It might be because my nodebb is set to use en_US and the languages in the OF install are marked as en_GB

**Comment by psychobunny** [comment]
Ah yes, that would be the reason then. I'll setup a transifex project for OF, this should take care of that problem 

https://github.com/psychobunny/nodebb-plugin-openfantasy/issues/3
